/*
	Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
	
	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	
	Find the sum of all the even-valued terms in the sequence which do not exceed four million.
*/

#include<stdio.h>

main()
{
	int a=0,aux=0;
	int i=0,j=2;

	while (j<=4000000)
	{
		aux=j;
		a+=j;
		j=j*4+i;
		i=aux;
	}

	printf("%i",a);
}
